### ISSUE TITLE
Error on open stream:api/channel/grid?start=0&limit=5000

### ISSUE THREAD

**Issue by NeySlim** [segator/proxylive#22]
Hi,

With latest docker image, I've got problems setting up tvheadend. Looks like the url in not reported building the channel list:

```
ERROR [main] org.springframework.boot.SpringApplication: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'streamController': Unsatisfied dependency expressed through field 'channelService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService': Invocation of init method failed; nested exception is java.io.IOException: Error on open stream:api/channel/grid?start=0&limit=5000
```

Configuration:

```
source:
    tvheadendURL: http://user:user01@192.168.1.45:9981
    channels:
        type: tvheadend
        refresh: 60
    reconnectTimeout: 3 
streamTimeout: 30
ffmpeg:
    path: ffmpeg
    profiles:
        -
            alias: "aac"
            #FFmpeg parameters, check ffmpeg documentation for more info
            parameters: "-i {input} {channelParameters} -sn -ac 2 -c:a libfdk_aac -b:a:0 128k  -b:a:1 96k  -b:a:2 128k -c:v copy -c:s copy"
        -
            alias: "copy"
            parameters: "-i {input} {channelParameters} -sn -c:a copy -c:v copy -c:s copy"
    mpegTS:
        parameters: "-threads 0 -f mpegts -mpegts_m2ts_mode 1 -mpegts_copyts 1 -mpegts_flags +resend_headers  -nostats -hide_banner"
    hls:
        tempPath: "/tmp"
        parameters: "-flags -global_header  -avoid_negative_ts disabled -map_metadata -1 -start_at_zero -copyts -flags -global_header -vsync cfr -y -nostats -hide_banner -f hls  -hls_time 2 -hls_list_size 10  -hls_flags delete_segments  -hls_flags +append_list -hls_flags +discont_start -hls_flags +delete_segments"
        timeout: 30

buffers:
    chunkSize: 131072
    broadcastBufferSize: 52428800
```
